### ISSUE TITLE
Anything to take from Fortran?

### ISSUE THREAD

**Issue by oscardssmith** [heltonmc/Bessels.jl#18]
https://github.com/arjenmarkus/specfunc-fullerton

**Comment by heltonmc** [comment]
Looks like they only give routines for the modified Bessel function's of integer order. 

`besselk` is done with forward recurrence similar to us but they don't use the uniform asymptotic expansion for large orders so that routine will be much slower than ours at large orders.

`besseli` is done with backward recurrence which on quick glance it looks like they have to come back all the way to `besseli0` which will also be very slow for large argument.

I think our routines would be better but I haven't run their code to confirm obviously.

**Comment by oscardssmith** [comment]
makes sense. That's kind of what I had expected, but figured it was worth a look.

**Comment by heltonmc** [comment]
A general fall back method though for the modified versions would be helpful for non-integer orders.
I spent some time today looking at the details in https://arxiv.org/pdf/1209.1547.pdf for numerical integration that will work for any order.... the challenge I found was a very significant number of terms were needed (n>150) to get good accuracy which made it quite slow.

**Comment by oscardssmith** [comment]
is it better for `Float16` or `Float32` arguments?
